#!/bin/sh
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

if [ $# -eq 1 ]; then
    TAG=$1
else
    TAG=${TAG:-${VERSION}}
fi

docker build -t ieth:${TAG} .
echo build ieth:${TAG}

docker tag ieth:${TAG} harbor.raginghot.com.cn/guowenshuai/ieth:${TAG}
docker push harbor.raginghot.com.cn/guowenshuai/ieth:${TAG}
