/*
 * ieth
 *
 * ieth 工具
 *
 * API version: last
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type InlineResponse2003 struct {
	Code float32 `json:"code,omitempty"`
	ErrMessage string `json:"errMessage,omitempty"`
	Data []string `json:"data,omitempty"`
}
