/*
 * ieth
 *
 * ieth 工具
 *
 * API version: last
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type EmptyObject6 struct {
	// 存储几份
	Duplicate int32 `json:"duplicate"`
	// 存储时长
	Duration int32 `json:"duration"`
	// 存储单价
	Price string `json:"price"`
	// 发单到存储市场
	Market bool `json:"market"`
	// 钱包地址
	Wallet string `json:"wallet"`
	// 发送多少单
	Nums int32 `json:"nums"`
}
