/*
 * ieth
 *
 * ieth 工具
 *
 * API version: last
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type InlineResponse200Data struct {
	Hash string `json:"Hash"`
	Name string `json:"Name"`
	Size float32 `json:"Size"`
	Type_ float32 `json:"Type"`
}
