/*
 * ieth
 *
 * ieth 工具
 *
 * API version: last
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type EmptyObject struct {
	// 是否递归
	Recursive bool `json:"recursive"`
	// cid
	Cid string `json:"cid"`
}
