/*
 * ieth
 *
 * ieth 工具
 *
 * API version: last
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type InlineResponse2002Data struct {
	Expiry string `json:"expiry"`
	MaxSize string `json:"max_size"`
	MinSize string `json:"min_size"`
	Miner string `json:"miner"`
	PricePerGib string `json:"price_per_gib"`
	Seqno string `json:"seqno"`
	Timestamp string `json:"timestamp"`
	VerifiedPricePerGib string `json:"verified_price_per_gib"`
}
